version: "3"
services:
  oauth:
    image: registry.cn-beijing.aliyuncs.com/codeforfun/oauth:1.0.1
    build: .
    environment:
      REDIS_ENABLE: 'true'
    ports:
      - "12222:8080"
  mysql:
    image: mysql:5.7.27
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  redis:
    image: redis:5.0.5-alpine
    ports:
      - "6379:6379"