spring:
  application:
    name: ${SPRING_APPLICATION_NAME:oauth}
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: jdbc:mysql://${DB_URL:mysql}:${DB_PORT:3306}/${DB_NAME:oauth}?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    enable: ${REDIS_ENABLE:false}
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    cache-timeout: ${REDIS_CACHE_TIMEOUT:120}
    embedded-enable: ${REDIS_EMBEDDED_ENABLE:false}
server:
  port: ${SERVER_PORT:8080}